### ISSUE TITLE
Add dependency and features for time crate

### ISSUE THREAD

**Issue by allsey87** [WorldSEnder/tracing-web#1]
I think there might be an issue in this crates Cargo.toml, I needed to add this line to get things working:
```
time = { version = "0.3.20", features = ["wasm-bindgen"] }
```
Since this is a tracing-web crate, I guess this feature should always be enabled, right? Or at least I think this should be mentioned in the README and example.

**Comment by WorldSEnder** [comment]
You are right, that feature needs to be enabled for `.with_timer(UtcTime::rfc_3339())` to work. Easy to miss due to feature unification (i.e. only has to be enabled *somewhere* in the dependency tree). I will add a note to the docs. Since this crate does not explicitly depend on `time`, and is only using it as transitive dependency and in the example, I'd rather not have it as a dependency on `tracing-web` directly. Perhaps in the future, `time` will automatically detect wasm-bindgen targets and make the feature obsolete.
