### ISSUE TITLE
Colorful logs

### ISSUE THREAD

**Issue by axelkar** [WorldSEnder/tracing-web#4]
Thank you for the crate! Could you add colorful logging like in the `wasm-log` crate?
<https://lib.rs/crates/wasm-log>
![img](https://raw.githubusercontent.com/s1gtrap/wasm-log/a37e2ef9410ffe30dc2c81b044d3e8a26e5bc085/Screenshot.png)

**Comment by WorldSEnder** [comment]
Since I do not see a simple way to break apart the log messages this crate receives from the underlying `tracing` architecture, I don't see how to achieve this without breaking the layering abstractions. The [`ConsoleWriter`](https://github.com/WorldSEnder/tracing-web/blob/master/src/console_writer.rs#L28) just does not receive any helpful information how the message is formatted, it just works on the fully formatted message.

If you know a way to work around this, feel free to submit a PR.

In my personal opinion, the filtering the browser tools give you to filter by log level are often sufficient to find what I'm looking for. Consider that you can change the levels per module or log location with the tracing framework, even at runtime, to enable or disable interesting statements - refer to their docs for details.

**Comment by axelkar** [comment]
I don't mean the file location, but the colored log level. I see you can get the level in [`MakeWriter::make_writer_for`](https://github.com/WorldSEnder/tracing-web/blob/master/src/console_writer.rs#L77-L88). Could you explain a little more?

**Comment by WorldSEnder** [comment]
I see what you mean now, I had the assumption you were interested in the emboldened file location too. Yes, I suppose having an option to add a label for the log level to the message can make sense. Are you interested in submitting a PR for it?

**Comment by WorldSEnder** [comment]
See the linked pull request for code samples and how to use the new writer. I will publish 0.1.3 asap.
